import io
import datetime
import pandas as pd
import plotly.io as pio
from docx import Document
from docx.shared import Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH


def _fig_to_png_stream(fig, width: int = 900, height: int = 480):
    try:
        png = pio.to_image(fig, format="png", width=width, height=height, scale=1.5)
        return io.BytesIO(png)
    except Exception:
        return None


def _add_chart(doc, fig, width_in: float = 6.0):
    if fig is None:
        doc.add_paragraph("Not available.")
        return
    stream = _fig_to_png_stream(fig)
    if stream is None:
        doc.add_paragraph("Chart unavailable (rendering failed).")
        return
    doc.add_picture(stream, width=Inches(width_in))
    doc.paragraphs[-1].alignment = WD_ALIGN_PARAGRAPH.CENTER


def _set_header_cell(cell, text):
    cell.text = text
    cell.paragraphs[0].runs[0].bold = True


def _add_deg_table(doc, top_degs: pd.DataFrame):
    cols = ["Gene", "log2FoldChange", "pvalue", "padj", "significance"]
    df = top_degs[cols].head(30)
    table = doc.add_table(rows=1, cols=len(cols))
    table.style = "Light Grid Accent 1"
    for i, col in enumerate(cols):
        _set_header_cell(table.rows[0].cells[i], col)
    for _, row in df.iterrows():
        cells = table.add_row().cells
        cells[0].text = str(row["Gene"])
        cells[1].text = f"{row['log2FoldChange']:.3f}"
        cells[2].text = f"{row['pvalue']:.2e}"
        cells[3].text = f"{row['padj']:.2e}"
        cells[4].text = str(row["significance"])


def generate_docx_report(
    dataset_label: str,
    summary: dict,
    results: pd.DataFrame,
    ml_results: dict,
    top_degs: pd.DataFrame,
    fig_volcano,
    fig_heatmap,
    fig_pca,
    fig_bar,
    interpretation: str = "",
) -> bytes:
    now = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    doc = Document()

    doc.add_heading("GeneLens Analysis Report", level=0)
    meta = doc.add_paragraph()
    meta.add_run(f"Dataset: {dataset_label}    ·    Generated: {now}").italic = True

    doc.add_heading("Summary", level=1)
    labels = ["Total Genes", "Upregulated", "Downregulated", "Not Significant", "ML CV AUC"]
    values = [
        f"{summary['total_genes']:,}",
        f"{summary['upregulated']:,}",
        f"{summary['downregulated']:,}",
        f"{summary['not_significant']:,}",
        f"{ml_results['accuracy']:.3f}",
    ]
    summary_table = doc.add_table(rows=2, cols=len(labels))
    summary_table.style = "Light Grid Accent 1"
    for i, lbl in enumerate(labels):
        _set_header_cell(summary_table.rows[0].cells[i], lbl)
    for i, val in enumerate(values):
        summary_table.rows[1].cells[i].text = val

    doc.add_heading("Differential Expression", level=1)
    _add_chart(doc, fig_volcano)
    _add_chart(doc, fig_bar, width_in=4.0)

    doc.add_heading("Heatmap — Top DE Genes", level=1)
    _add_chart(doc, fig_heatmap)

    doc.add_heading("PCA — Sample Clustering", level=1)
    if fig_pca:
        _add_chart(doc, fig_pca)
    else:
        doc.add_paragraph("PCA not available (need ≥2 samples per group).")

    doc.add_heading("Machine Learning Classification", level=1)
    _add_chart(doc, ml_results.get("roc_fig"), width_in=4.0)
    _add_chart(doc, ml_results.get("importance_fig"), width_in=4.5)
    ml_p = doc.add_paragraph()
    ml_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    ml_p.add_run(
        f"Cross-Validation AUC: {ml_results['accuracy']:.3f} ± {ml_results['std']:.3f}   |   "
        f"Features: {ml_results['n_features']} genes"
    )

    doc.add_heading("Top DE Genes", level=1)
    _add_deg_table(doc, top_degs)

    if interpretation:
        doc.add_heading("AI Biological Interpretation", level=1)
        doc.add_paragraph(interpretation)

    doc.add_paragraph()
    footer1 = doc.add_paragraph()
    footer1.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer1.add_run("Generated by GeneLens — Real Gene Expression Analysis").bold = True
    footer2 = doc.add_paragraph()
    footer2.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer2.add_run("genelens.streamlit.app").italic = True

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
